### ISSUE TITLE
html 관련 수정사항

### ISSUE THREAD

**Issue by hallov012** [djLeeeee/project1#37]
1. plan_date: 
  * 날짜 출력
  * title 밑에 장소로 출력하게 수정
2. index
  * 버튼 영역 수정(빈 공간을 눌러도 plan_date로 이동하는 문제)
  * "서울 3반 약속 번개잡기" 삭제
  * create 버튼을 navbar 항목으로 만들기
  *  약속 개수 출력 이쁘게

**Comment by hallov012** [comment]
index 수정 완료

**Comment by djLeeeee** [comment]
수정 완료
