### ISSUE TITLE
회원가입시 first_name, last_name을 입력 안해도 가입이 진행되는 문제

### ISSUE THREAD

**Issue by hallov012** [djLeeeee/project1#39]
detail 페이지에서 작성자 아이디가 아닌 이름을 띄어주기 때문에 두 항목이 필수적으로 입력되어야하는데 현재 회원가입은 이 둘에 대한 입력값 없이도 가입이 진행됨

**Comment by hallov012** [comment]
accounts/models.py 에서 User에 first_name, last_name 을 추가해줘야 함
```python
class User(AbstractUser):
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
```

-----------------------------------------------------------
* django의 AbstractUser 에도 first_name, last_name 항목이 있는데 회원가입시 필수로 입력해야하는 항목으로 설정되지 않는 이유
> django 내의 AbstractUser 내의 두 항목은 `blank=True` 로 설정되어 있기 때문에 빈 값을 입력해도 `is_valid()`에서 걸러주지 못한다
```python 
# django.contrib.auth.models
first_name = models.CharField(_('first name'), max_length=150, blank=True)
last_name = models.CharField(_('last name'), max_length=150, blank=True)
```
따라서 필수값으로 입력을 해주기 위해서는 User에서 새로 정의해줘야한다

**Comment by djLeeeee** [comment]
[django.db.models.fields.__init__.py](https://github.com/django/django/blob/main/django/db/models/fields/__init__.py#L187)

`blank` 부분의 default 값이 `False`로 되어 있음.
