### ISSUE TITLE
css 파일 변경 후 변경사항이 적용되지 않는 문제

### ISSUE THREAD

**Issue by hallov012** [djLeeeee/project1#44]
css 파일을 수정 후 저장했지만 runserver로 실행해 보면 수정 전 css 파일을 읽어와 변경 사항 적용이 되지 않음

**Comment by Cr-Mo-Marco-3000** [comment]
두 가지 해결 방법이 있음.
1. 작업하는 브라우저의 쿠키를 삭제하고 다시 시도한다.
2. `<link rel="stylesheet" href="{% static 'plans/plan_create.css' %}?after ">` 
위와 같이, 문제가 일어나는 페이지의 stylesheet href "" 마지막에 ?after를 추가해 준다
